from pathlib import Path
import tomllib

with open("pyproject.toml", "rb") as f:
    version = tomllib.load(f)["tool"]["poetry"]["version"]

content = (
    "# This file is auto-generated by update_version.py. Do not edit manually.\n"
    "# The version is read from pyproject.toml and written to this file for use in the package.\n"
    f'__version__ = "{version}"\n'
)

Path("version.py").write_text(
    content
)
    

