from pathlib import Path
import json
import tomllib

# Read version from pyproject.toml
with open("pyproject.toml", "rb") as f:
    version = tomllib.load(f)["tool"]["poetry"]["version"]

# Update version.py
version_py_content = (
    "# This file is auto-generated by update_version.py. Do not edit manually.\n"
    "# The version is read from pyproject.toml and written to this file for use in the package.\n"
    f'__version__ = "{version}"\n'
)

Path("version.py").write_text(version_py_content, encoding="utf-8")

# Update codemeta.json
codemeta_path = Path("codemeta.json")

if codemeta_path.exists():
    with codemeta_path.open("r", encoding="utf-8") as f:
        codemeta = json.load(f)

    codemeta["version"] = version

    with codemeta_path.open("w", encoding="utf-8") as f:
        json.dump(codemeta, f, indent=2, ensure_ascii=False)
        f.write("\n")

print(f"Updated version.py and codemeta.json to version {version}")


